### ISSUE TITLE
Mail catcher doesn't work given the default set up

### ISSUE THREAD

**Issue by Jezzamonn** [ludumdare/dairybox#24]
Following the instructions on the page, I was unable to get mailcatcher to 'catch' any emails. After building the site and running mailcatcher using the script, I clicked the new account button, but the mailcatcher page still didn't show any emails. The user was created in the database, and I was able to activate an account using the activation url from the database, however. I tried this for two separate email addresses, to no success.

**Comment by mikekasprzak** [comment]
Can you be a bit more specific about your setup?

Also, did you run it from inside the VM (`vagrant ssh; ./start_mailcatcher.sh`)?

**Comment by mikekasprzak** [comment]
Ah actually, it looks like it's not actually sending e-mails at all.

**Comment by mikekasprzak** [comment]
Okay, this should be fixed now. You'll have to update both Dairybox and the Ludum Dare code, as well as do a `vagrant destroy`.
