### ISSUE TITLE
$NPM_INSTALL_ARGS are only set if using Cygwin, not Git Bash

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/dairybox#30]
# $NPM_INSTALL_ARGS are only set if using Cygwin, not Git Bash
## Issue
npm install fails when doing ```vagrant up``` from git bash on windows. Giving the errors below
```
==> default: npm ERR!
==> default:  Linux 3.13.0-55-generic
==> default: npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
==> default: npm ERR! node v5.0.0
==> default: npm ERR! npm  v3.3.6
==> default: npm ERR! path ../acorn/bin/acorn
==> default: npm ERR! code EPROTO
==> default: npm ERR! errno -71
==> default: npm ERR! syscall symlink
==> default:
```
## Cause
Currently if your on windows and using Cygwin then we use the --no-bin-links flag to avoid issues with windows weird handling of links. But we don't do this if your on windows and using git bash.
```
if [ `uname -o` = "Cygwin" ]
then
	NPM_INSTALL_ARGS=--no-bin-links
else
	NPM_INSTALL_ARGS=
fi
```
## Possible Solution
So we should probably change it to this 
```
if [ `uname -o` = "Cygwin" ]||[ `uname -o` = "Msys" ]
then
	NPM_INSTALL_ARGS=--no-bin-links
else
	NPM_INSTALL_ARGS=
fi
```
I haven't tested this yet so it may not fix the issue. If it works  when i test it i'll make a pull request. But there a few other issues to deal with.

**Comment by mikekasprzak** [comment]
When I tested it in the GIT Bash Shell, despite any errors, I actually had no issues running the toolchain. Admittedly I didn't do a very exhaustive test though, and I did click a checkbox during GIT install that said something about Symlink support.

Also FWIW, I think it may be possible to do setup without any Unix shell installed at all. It just has the benefit of giving you a better terminal interface (re-sizable w/ colors) when you do `vagrant ssh`. 

That said, I'm not even sure the `--no-bin-links` code is working at all, as the NPM calls are happening inside the VM on a virtual Linux machine (where `uname -o` would return something Linux). So the real trick is figuring out from the VM if it's on a Windows host, to THEN include `--no-bin-links`.

**Comment by mikekasprzak** [comment]
This is probably what's needed:

http://stackoverflow.com/a/39125251/5678759

**Comment by zwrawr** [comment]
Good point about needing to know in the VM. I didn't think about that.

Maybe thats why the links in ~/ (e.g. ~/www created in bootstrap.sh) were all fine. But the /-/ links didn't work (there created in www/Scripts/setup.sh)

**Comment by mikekasprzak** [comment]
I'm currently testing some code in the Vagrantfile to (hopefully) let us figure out if we're on a Windows host or not. From that I should be able to adapt the original non-working code to check that instead.

**Comment by mikekasprzak** [comment]
Okay, this *should* be fixed now.

**Comment by povrazor** [comment]
Ah, this actually highlights a different issue now.

```
==> default: Done (Apache Ports).
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-ludumdare.com/-/all.js’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-ludumdare.com/-/all.css’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-ludumdare.com/-/all.svg’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.vg/-/all.js’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.vg/-/all.css’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.vg/-/all.svg’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.bio/-/all.js’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.bio/-/all.css’
==> default: : Protocol error
==> default: ln:
==> default: failed to create symbolic link ‘/vagrant/www/public-jammer.bio/-/all.svg’
==> default: : Protocol error
```

Still symlink related, but nothing to do with npm and node this time.

**Comment by mikekasprzak** [comment]
Ah, well it did fix things ... sort of. `--no-bin-links` however ends up breaking npm and node support in general. Lovely.

Currently trying an alternative to `--no-bin-links`.

**Comment by mikekasprzak** [comment]
Alright, **now** it should be fixed.

**IMPORTANT**: You must run your shell (bash, cmd) as an Administrator. This is required for Windows to correctly support symlinks.

EDIT: Cool. Even debug mode is working.

**Comment by zwrawr** [comment]
Nice, It works for me now. 😀
