### ISSUE TITLE
Toolchain fails to build preact 8.1.0

### ISSUE THREAD

**Issue by mkalam-alami** [ludumdare/dairybox#40]
With a fresh Vagrant VM I get the following error during a `make`:

```
rollup -c src/config/rollup.config.js .output/public-jammer.vg/main-vg.es6.js > .output/.build/public-jammer.vg/buble.js.tmp
🚨   Could not resolve '../dom' from /vagrant/www/.output/external/preact/vdom/diff.es6.js
```

I tried tinkering with plugins in the rollup config file, without success.
As a workaround, downgrading preact to v7.2.0 fixed the issue.

**Comment by mikekasprzak** [comment]
Weird. I'm running it on 2 machines fine, plus the live server.

**Comment by zwrawr** [comment]
Did you get this working now?

**Comment by mkalam-alami** [comment]
@zwrawr Well I wanted to test it again but I can't even `vagrant up` right now, I think my setup's broken :P I'll report my findings after reinstalling everything!

**Comment by mikekasprzak** [comment]
Hey it's been a few months. We've helped a few more folks get the toolchain working for them. Are you interested in trying again, or should we just close this?

**Comment by mkalam-alami** [comment]
Oh sorry, I didn't push further in the end. Let's say I reopen if I get the issue again. Thanks!
