### ISSUE TITLE
Mount 'node_modules' folder by default

### ISSUE THREAD

**Issue by zwrawr** [ludumdare/dairybox#50]
* @sgstair 
> crazy idea: mount node_modules

In our testing this is a significant performance upgrade when compiling.

I got 8m52s --> 6m24s
and @sgstair got 16m59s --> 9m54s

**Comment by sgstair** [comment]
Thanks for following up, I should have filed this issue a while back :)

**Comment by mikekasprzak** [comment]
Should be safe even for non-windows. Might be doable right from the Vagrantfile (For best compatibility).

If I recall the command for doing it manually looks something like this.

```
mkdir ~/.node_modules
cd ~/www
sudo mount --bind /home/vagrant/.node_modules node_modules
```

Vagrantfile is a bit trickier, but there are other mounts in the Vagrantfile, and the Vagrant manual should tell us what's different.

During install too, the `~/www/node_modules` folder might need to be created.
