### ISSUE TITLE
404 when running box update

### ISSUE THREAD

**Issue by local-minimum** [ludumdare/dairybox#57]
![image](https://user-images.githubusercontent.com/8041100/41304760-57cd6844-6e71-11e8-9129-895c5965d1d8.png)

**Comment by mikekasprzak** [comment]
Awesome. Okay, I'll escalate getting my custom box going, 'cause apparently
we can't work without it now. Thanks Scotch.io 😑

**Comment by local-minimum** [comment]
I could get it to start though even after I had destroyed my vagrant, so it might not be as critical as it could seem

**Comment by mikekasprzak** [comment]
That's probably because you have the a copy of the VM (box) locally. If you
try to install the toolchain on a fresh PC, and it 404's, you're out of
luck.

**Comment by zwrawr** [comment]
I don't see a 404 running this
```
zwrawr@sol /storage/Repos/DairyBox (dairybox) (master) $ vagrant box update
==> default: Checking for updates to 'scotch/box'
    default: Latest installed version: 2.5
    default: Version constraints: 2.5
    default: Provider: virtualbox
==> default: Box 'scotch/box' (v2.5) is running the latest version.
```

**Comment by mikekasprzak** [comment]
Now running 3.5 thanks to @zwrawr
