### ISSUE TITLE
PHP 7.x instead of 5.6 in VM

### ISSUE THREAD

**Issue by mikekasprzak** [ludumdare/dairybox#7]

**Comment by mikekasprzak** [comment]
NOTE: When I tested this initially (i.e. before PHP 7's launch), I was unable to get this working. It may work now, as long as there is a PPA repository for PHP 7 somewhere.

**Comment by martindilling** [comment]
With the release of 7.1.0, that might be the one to work towards :)
http://php.net/archive/2016.php#id2016-12-01-3

**Comment by mikekasprzak** [comment]
I did an experiment today, and I was able to get mainline PHP 7 working in the VM, but it does generate a lot of errors along the way.

See over here for details how to do this manually: https://github.com/ludumdare/ludumdare/issues/221
